### ISSUE TITLE
LabelsToTags.lua:147: attempt to call a nil value (global 'unpack')

### ISSUE THREAD

**Issue by manu-p** [darktable-org/lua-scripts#106]
Hi, I'm trying to setup and use the LUA script following the installation and usage sections as provided.

I chose the following in luarc:
```
require "LabelsToTags"
darktable.register_tag_mapping("Example", { ["+----*"] = { "Red", "Only red" } })
```
Here's what I get when starting dt with the '-d lua' option:
`LUA ERROR : /home/manu/.config/darktable/lua/LabelsToTags.lua:147: attempt to call a nil value (global 'unpack')`

What do I miss? Thanks.

**Comment by houz** [comment]
That script isn't compatible with darktable 2.4 it seems. Lua 5.3 no longer has the `unpack` command. A quick google search indicates that it's now `table.unpack`.

**Comment by manu-p** [comment]
OK, thanks. So I guess I have to add 'table.' to the beginning of line 147.

Now, here's the output I get from -d lua:
`LUA ERROR : /home/manu/.config/darktable/luarc:11: attempt to index a nil value (global 'darktable')`

Line 11 is the one with: 
`darktable.register_tag_mapping("Example", { ["+----*"] = { "Red", "Only red" } })`
