### ISSUE TITLE
attempt to index a nil value (global 'darktable')

### ISSUE THREAD

**Issue by manu-p** [darktable-org/lua-scripts#107]
After solving (?) a [former issue](https://github.com/darktable-org/lua-scripts/issues/106) due to Lua 5.3, I'm now facing a new error while trying to run this lua script:

`LUA ERROR : /home/manu/.config/darktable/luarc:11: attempt to index a nil value (global 'darktable')`

Line 11 is the one in luarc with:
darktable.register_tag_mapping("Example", { ["+----*"] = { "Red", "Only red" } })

just following  : 
`require "LabelsToTags"`

**Comment by houz** [comment]
Do you also have `local darktable = require "darktable"` in your luarc? Whenever Lua tells you something is a nil value then it's not defined. And in your case there is no object `darktable`. At least that's what I suppose is happening.

**Comment by manu-p** [comment]
OK, that was it. May I suggest you to specify it in the installation section? Thank you.

**Comment by chrik5** [comment]
Why? It is part of the LUA script `LabelsToTags` and part of the official documentation.

**Comment by houz** [comment]
I guess what he meas is the comments about how to use the script inside the script?

**Comment by wpferguson** [comment]
Can we close this?

**Comment by houz** [comment]
Probably.
