### ISSUE TITLE
group rating plugin does not update view the way normal rating does

### ISSUE THREAD

**Issue by anarcat** [darktable-org/lua-scripts#125]
I have tried to use the `contrib/rate_group.lua` plugin and I think it's very useful! Unfortunately, it doesn't behave the same way the normal rating shortcut does. In my workflow, I often filter displayed images to "unstarred only", which makes Darktable hide the image as soon as I rate it, using the normal shortcut. If I use the `rate_group` plugin instead, the image stays visible after rating, even though it should be hidden.

Incidentally, calling the `rate_group` shortcut and *then* calling the normal rating shortcut redisplays the view correctly, but it's hardly a good enough workaround... :)

I looked in the DT source and in `ratings.c`, the rating function seems to call `_update_collected_images` after setting the rating. No such callback exists on the Lua side so I am wondering if there's an easy way to fix this or it would require introducing a new API in Lua...

**Comment by wpferguson** [comment]
You could try adding dt.gui.current_view = "lighttable".  This might cause the view to reload and perform a _update_collected_images as part of the reload.  However, darktable may be smart enough to realize that the current view is already lighttable and not do anything.

**Comment by anarcat** [comment]
i tried the following:

```diff
diff --git a/contrib/rate_group.lua b/contrib/rate_group.lua
index 3a557a8..7736b49 100644
--- a/contrib/rate_group.lua
+++ b/contrib/rate_group.lua
@@ -56,6 +56,7 @@ local function apply_rating(rating)
   else
       dt.print("applying rating " ..rating.. " to group(s)")
   end
+  dt.gui.current_view = "lighttable"
 end
 
 dt.register_event("shortcut",function(event, shortcut)
```

and that didn't seem to work: the rating gets applied, without effect.

i also tried:

```diff
diff --git a/contrib/rate_group.lua b/contrib/rate_group.lua
index 3a557a8..a89b2c0 100644
--- a/contrib/rate_group.lua
+++ b/contrib/rate_group.lua
@@ -56,6 +56,8 @@ local function apply_rating(rating)
   else
       dt.print("applying rating " ..rating.. " to group(s)")
   end
+  dt.gui.current_view = "lighttable"
+  dt.gui.current_view()
 end
 
 dt.register_event("shortcut",function(event, shortcut)
```

no luck. any other ideas?

**Comment by wpferguson** [comment]
How about re-importing the changed images?

**Comment by wpferguson** [comment]
I'm getting ready to make some changes to the API and the rating will part of it, so maybe we can clear this after that happens.  It won't happen any earlier than 2.6.2, so it's still a few months away...

**Comment by anarcat** [comment]
considering that the 2.6 release has improved the rating workflow so that grouped images are tagged together, i don't know if this is still relevant so can probably be closed

**Comment by wpferguson** [comment]
I'll close it, but if it crops up again we can reopen this.
