### ISSUE TITLE
Use darktable as batch image processing without UI

### ISSUE THREAD

**Issue by lrapetti** [darktable-org/lua-scripts#127]
Is it possible to use lua-scripts in order to execute darktable batch processing without the user interface?
I am looking for batch loading images, correcting the lens and saving it, is there any example around?

**Comment by supertobi** [comment]
This is not a help forum but a bug tracker, please use the darktable mailing list for such questions.
Yes with:
darktable --luacmd <lua command>

    A string containing lua commands to execute after lua initialization. These commands will be run after your “luarc” file.

    If lua is not compiled in, this option will be accepted but won't do anything.

You can find an example in the gimp code:
https://gitlab.gnome.org/GNOME/gimp/blob/master/plug-ins/file-raw/file-darktable.c
https://gitlab.gnome.org/GNOME/gimp/tree/master/plug-ins/file-raw
