### ISSUE TITLE
`darktable -u lua` not valid option

### ISSUE THREAD

**Issue by lrapetti** [darktable-org/lua-scripts#128]
I am trying to use the darktable lua-scripts. I have installed darktable from [here](https://github.com/darktable-org/darktable), and I have followed the instruction at https://github.com/darktable-org/lua-scripts/edit/master/README.md#L97.

However when launching `darktable -u lua`, seems the option is non valid and I get:
```
$ darktable -u lua
usage: darktable [options] [IMG_1234.{RAW,..}|image_folder/]

options:

  --cachedir <user cache directory>
  --conf <key>=<value>
  --configdir <user config directory>
  -d {all,cache,camctl,camsupport,control,dev,fswatch,input,lighttable,
      lua, masks,memory,nan,opencl,perf,pwstorage,print,sql}
  --datadir <data directory>
  --disable-opencl
  -h, --help
  --library <library file>
  --localedir <locale directory>
  --luacmd <lua command>
  --moduledir <module directory>
  --noiseprofiles <noiseprofiles json file>
  -t <num openmp threads>
  --tmpdir <tmp directory>
  --version
```

Is there any specific configuration I should activate when installing darktable?

**Comment by supertobi** [comment]
It's "darktable -d lua" and not "darktable -u lua"
