### ISSUE TITLE
recent versions of enfuse don't accept the --exposure-mu parameter

### ISSUE THREAD

**Issue by HJarausch** [darktable-org/lua-scripts#136]
I had to apply the following patch
--- enfuse.lua	2018-08-10 13:54:56.516754118 +0200
+++ /home/jarausch/.config/darktable/lua/official/enfuse.lua	2018-08-11 14:06:12.093931704 +0200
@@ -139,7 +139,7 @@
         local ugly_decimal_point_hack = string.gsub(string.format("%.04f", mu), ",", ".")
         -- TODO: make filename unique
         local output_image = target_dir.."/enfuse.tiff"
-        local command = "enfuse --depth "..depth.value.." --exposure-mu "..ugly_decimal_point_hack
+        local command = "enfuse --depth "..depth.value.." --exposure-optimum "..ugly_decimal_point_hack
                         .." -o \""..output_image.."\" \"@"..response_file.."\""
         if dt.control.execute( command) > 0 then
           dt.print("enfuse failed, see terminal output for details")

**Comment by supertobi** [comment]
Could you please make a pull request, or mark the patch as code, so it doesn't get formatted from github?

And do you know the version, that has changed is parameter? Perhaps it is possible to make it compatible with both version by checking the version number.

**Comment by wpferguson** [comment]
If we apply that patch, then enfuse.lua will no longer work with enfuse 4.0.  If we want to make enfuse.lua 4.0 and 4.2 compatible, then we should use version detection and format the arguments accordingly.  Enfuse 4.0 is still the current version of enfuse on Ubuntu 16.04 LTS.

**Comment by wpferguson** [comment]
Added version awareness to enfuse.  PR submitted.

**Comment by supertobi** [comment]
Then please close this issue, after pushing the PR.
