### ISSUE TITLE
lua manager

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/lua-scripts#152]
I've seen that there is the excellent script_manager from wpferguson!

To install it one need to copy it to luarc. I'm wondering if it won't be nice to have darktable looking for also manager-luarc or something like that to make it possible to have some home-made lua scripts (activated in luarc) and at the same time have the manager activated.

What do you think?

**Comment by TurboGit** [comment]
Forget about this, I found that this is already supported by using the "downloads" directory. It is good to read the doc :)

**Comment by wpferguson** [comment]
It's also included in the tools directory in the lua-scripts distribution,
so you could set up a luarc and require whatever files you want, then
require tools/script_manager...

Bill
