### ISSUE TITLE
Lua script is not importing images in Darktable

### ISSUE THREAD

**Issue by sekaiii** [darktable-org/lua-scripts#159]
Hello guys,

here is the lua script

```
dt = require “darktable”
dt.films.new(“DirectoryA”)
dt.database.import(“DirectoryA") -- seem partly working it create xmp files in DirectoryA
```
What am I missing here ?

https://discuss.pixls.us/t/darktable-lua-script-help-needed/11048

**Comment by wpferguson** [comment]
Closing this issue because it's not an issue with any script in the lua-scripts repository.  Will continue to support it on https://discuss.pixls.us/darktable-lua-script-help-needed/11048
