### ISSUE TITLE
File name/path sanitizing

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/lua-scripts#191]
Recently a PR was submitted to add file name/path sanitizing to the dtutils.file mkdir/rmdir functions.  Since this issue affects all the file/directory name/path functions and the solution needs to be consistent across all of them, I closed the PR and opened an issue so that we could discuss it and arrive at a consensus.

Currently dutils.file supplies the function sanitize_filename() which provides OS specific file/path quoting.  The script developer is expected to pass sanitized strings to the file/directory name/path functions, though it's not explicitly spelled out in the documentation. 

I see the following options:

1.  We do nothing and leave everything as is.

2.  We update the documentation and spell out that sanitized strings are expected to be passed as arguments.

3.  We update sanitize_filename() to check if the string is already sanitized.  If it is, then just return it otherwise sanitize the string and return it.  Then we put a call to sanitize_filename into each file/directory name/path function to check the argument and fix it if necessary.  This will probably require some type of automated test suite to ensure it works correctly for all cases.

4. ????

**Comment by wpferguson** [comment]
@theres I couldn't assign you, but please participate

**Comment by wpferguson** [comment]
@BzKevin and any others I missed, please feel free to participate

**Comment by theres** [comment]
Sure. I kind of opt for option 3, i.e. I'd expect that `sanitize_filename` is idempotent. This seems to be the safest for use, but of course is the hardest to implement in the library itself.  Anyway, I think it's good idea to keep all the hard logic in one place, even if the logic itself will get some additional complexity.

And of course +1 for unit testing.

**Comment by wpferguson** [comment]
@theres `sanitize_filename` should be idempotent, but it's not.  I'll fix that whichever way we decide on the rest.

My opinion is that 1 is the easiest and 3 is the best and correct way to fix it.

As far as unit testing I'm thinking about LuaUnit.  My first thought was cucumber, but that introduces too many external dependencies whereas LuaUnit is self-contained and can be bundled with the distribution.  I'll have to dummy up a darktable library that at least returns the configuration information and handles print[_(error|log] statements.  Sounds like this might be my "darktable summer of code" project :-).

**Comment by AlicVB** [comment]
I think 3 is the best solution too. (As a lua "newbie" I've been quite surprised that mkdir doesn't just create the wanted directory...)
but again, I've absolutely no idea how non-linux OS works...

**Comment by wpferguson** [comment]
[test.zip](https://github.com/darktable-org/lua-scripts/files/3352631/test.zip)

I played with setting up testing.  The attached zip file will give you an idea of what I'm thinking.  Just go in your lua-scripts directory and create a directory `test`.  Unzip the test.zip file in there.  You can run the test_sanitize.lua file with `lua5.3 test_sanitize.lua`.  I'm running Ubuntu 18.04, so my lua executable is lua5.3.  Yours may be something different.

The darktable.lua file is my solution to `local dt = require "darktable"`.  Right now I've just stubbed some functions in order to get stuff to run.  I'm going to have to flesh them out and add more as testing expands.

**Comment by wpferguson** [comment]
While working on unit testing, found a bug with urlencode() in the string library.

I also found another benefit of the testing code.  You can do the following

`~/src/wpferguson/lua-scripts/test$ lua5.3
Lua 5.3.3  Copyright (C) 1994-2016 Lua.org, PUC-Rio
> dt = require "darktable"
> dt.set_personality("linux")
> ds = require "lib/dtutils.string"
> print(ds.sanitize("this string needs quotes"))
'this string needs quotes'
> print(ds.urlencode("this string isnt web safe"))
this+string+isnt+web+safe
> os.exit()`

so there is now a  way to interact with the libraries from the command line if you have questions about what they really do.

**Comment by wpferguson** [comment]
Fixed the string library.  Built unit tests.  PR submitted to get that merged.  In the meantime, I'll start on the file library.  Feel free to check out the PR and make comments on it.

**Comment by wpferguson** [comment]
I've started testing the file library.  As part of testing, I'm working on a darktable "emulator" so that we can do command line testing.  I was looking at emulating widgets and was having trouble passing the arguments, since we create widgets with the call

`widget = dt.new_widget(type){arguments}`

If you try passing that in Lua, it reads `(type)` and throws an error on` {arguments}`.  So, I went and looked at the Lua API manual and the correct syntax for new_widget is 

`widget = dt.new_widget(type, {arguments})`

I tried it and it works fine.  The reason the `(type){arguments}` passing works in darktable is because they are being sent to a C routine which can access the stack and still retrieve the arguments.

**Comment by wpferguson** [comment]
It seems that I spoke too soon.  I changed the widgets in the file library to use the documented calling sequence and wrote testing to use them and it worked fine.  Then I fired up darktable and started getting errors.  So, it seems that the correct calling sequence is dt.new_widget(type){arguments}.  I'm not sure it's valid lua, but it's what darktable accepts and understands.

**Comment by wpferguson** [comment]
Until I can figure out a better solution, I've come up with a hack to unit test code with new_widget functions.  I wrote a helper to "sanitize" the new_widget calls by changing the syntax from new_widget(type){args} to new_widget(type, {args]), writing the result to dt.configuration.tmp_dir, then loading it from there and testing it. The "sanitized" library file is left in dt.configuration.tmp_dir so it can be diffed to ensure no other changes were made.

**Comment by wpferguson** [comment]
Merged the file and string fixes discovered during testing.  The PR also included filename sanitizing.

Testing is a work in progress.  We can open an issue to discuss it if necessary.
