### ISSUE TITLE
windows error?

### ISSUE THREAD

**Issue by aster94** [darktable-org/lua-scripts#194]
maybe i am missing something but i followed the installation tutorial in the read me and i don't think that i missed any step

```
PS C:\Users\vincenzo\AppData\Local\darktable> ls


    Directory: C:\Users\vincenzo\AppData\Local\darktable


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       26/10/2019     11:33                lua
-a----       26/10/2019     12:12          23805 darktablerc
-a----       26/10/2019     12:10         151552 data.db
-a----       03/08/2019     12:22          95709 keyboardrc
-a----       26/10/2019     12:10          93180 keyboardrc_default
-a----       26/10/2019     12:12        4358144 library.db
-a----       26/10/2019     11:55            172 luarc


PS C:\Users\vincenzo\AppData\Local\darktable> cat luarc
require "contrib/gimp"
require "examples/hello_world"
PS C:\Users\vincenzo\AppData\Local\darktable> tree
Elenco del percorso delle cartelle
Numero di serie del volume: 2883-797C
C:.
└───lua
    ├───contrib
    ├───examples
    │   └───de_DE
    │       └───LC_MESSAGES
    ├───lib
    │   └───dtutils
    ├───locale
    │   ├───de_DE
    │   │   └───LC_MESSAGES
    │   └───fr_FR
    │       └───LC_MESSAGES
    ├───official
    └───tools
```

running `./darktable -d lua` i don't see print any hello world nor i see the gimp export

**Comment by wpferguson** [comment]
Which version of darktable are you using? 

When I'm debugging lua I start it from a command prompt in my home directory and redirect the output to log.txt, i.e. "\Program Files\darktable-2.7\bin\darktable.exe" -d lua > log.txt

type the log.txt file and see what it says

**Comment by aster94** [comment]
`4,411701 LUA ERROR : C:\Users\vincenzo\AppData\Local\darktable\luarc:1: unexpected symbol near '<\255>'`

weird, any idea?
here there is my luarc
[luarc.zip](https://github.com/darktable-org/lua-scripts/files/3775854/luarc.zip)

**Comment by wpferguson** [comment]
I'm not sure what you used  to create the luarc file, but it created a
binary file.  I dumped it and it looks like this:

0000000 377 376   r  \0   e  \0   q  \0   u  \0   i  \0   r  \0   e  \0
0000020      \0   "  \0   c  \0   o  \0   n  \0   t  \0   r  \0   i  \0
0000040   b  \0   /  \0   g  \0   i  \0   m  \0   p  \0   "  \0  \r  \0
0000060  \n  \0   r  \0   e  \0   q  \0   u  \0   i  \0   r  \0   e  \0
0000100      \0   "  \0   c  \0   o  \0   n  \0   t  \0   r  \0   i  \0
0000120   b  \0   /  \0   v  \0   i  \0   d  \0   e  \0   o  \0   _  \0
0000140   f  \0   f  \0   m  \0   p  \0   e  \0   g  \0   "  \0  \r  \0
0000160  \n  \0   r  \0   e  \0   q  \0   u  \0   i  \0   r  \0   e  \0
0000200      \0   "  \0   c  \0   o  \0   n  \0   t  \0   r  \0   i  \0
0000220   b  \0   /  \0   t  \0   i  \0   m  \0   e  \0   l  \0   a  \0
0000240   p  \0   s  \0   e  \0   "  \0  \r  \0  \n  \0   r  \0   e  \0
0000260   q  \0   u  \0   i  \0   r  \0   e  \0      \0   "  \0   e  \0
0000300   x  \0   a  \0   m  \0   p  \0   l  \0   e  \0   s  \0   /  \0
0000320   h  \0   e  \0   l  \0   l  \0   o  \0   _  \0   w  \0   o  \0
0000340   r  \0   l  \0   d  \0   "  \0  \r  \0  \n  \0
0000354

Then I created a luarc file and dumped it and it looks like this:

0000000   r   e   q   u   i   r   e       "   c   o   n   t   r   i   b
0000020   /   g   i   m   p   "  \r  \n   r   e   q   u   i   r   e
0000040   "   c   o   n   t   r   i   b   /   v   i   d   e   o   _   f
0000060   f   m   p   e   g   "  \r  \n   r   e   q   u   i   r   e
0000100   "   c   o   n   t   r   i   b   /   t   i   m   e   l   a   p
0000120   s   e   "  \r  \n   r   e   q   u   i   r   e       "   e   x
0000140   a   m   p   l   e   s   /   h   e   l   l   o   _   w   o   r
0000160   l   d   "  \r  \n  \r  \n
0000167

I usually use notepad when I edit the luarc file on windows and it
works fine.

I've included a luarc file (from the one I created), that should work.

**Comment by aster94** [comment]
😮😮 really i don't have any idea how that happened, I did right click and created a new document with notepad++ and removed the extension, funny behaviour

also i encountered another problem

> official/check_for_updates.lua:32: module 'ssl.https' not found

I am not very interested in resolving this so i just commented the official script out and now everything works perfectly but someone here may be interested in this

**Comment by wpferguson** [comment]
official/check_for_updates.lua requires an external dependency, i.e. the ssl.https module.  You could satisfy it by installing luarocks, then adding the required module, if you want.

**Comment by aster94** [comment]
ok, then i guess we can close the issue, thanks for the support!

**Comment by wpferguson** [comment]
You're welcome
