### ISSUE TITLE
dt 3.0 testing

### ISSUE THREAD

**Issue by ghost** [darktable-org/lua-scripts#198]
It seems that many scripts are not working with dt 3.0 anymore and require further testing. E.g. enfuseAdvanced and hugin are not even loading (at least on Linux). Debugging (-d lua) gives no output.

**Comment by wpferguson** [comment]
A little more information would be helpful

Does they work on 2.6.x?

Are you running a flatpak or a snap?

Have you updated your lua scripts in the last 10 months?

The api version number changed due to some additions to the lua api.  Nothing was removed from the api, so everything that worked on 2.6 should be working on 3.0.  We made a change to the scripts 10 months ago to handle the api change so that there wouldn't be an interruption or a lot of code changes at the last minute.

I just tested the scripts against darktable built from git last night and hugin and enfuseAdvanced both work for me.

If they are working for you on 2.6, then you have lua installed so that's not the problem.

If they run with 2.6 and not 3.0, then the scripts are probably out of date and are failing the api check.

**Comment by maxence33** [comment]
Hi, 
I am new to LUA scripts but I kinda have the same issue as @timur-davletshin 
I am not sure if this is me not doing things properly or if something is indeed not working..

I have the below `luarc`

.config/darktable/luarc

```
darktable = require "darktable"
require "official/enfuse"
require "contrib/enfuseAdvanced"
require "contrib/hugin"
require "contrib/image_stack"
require "contrib/gimp"
```

and I only get the "Enfuse" tab in the light table panel. Nothing from the contrib folder... unless I am not looking at the right place...

I have just cloned the lua scripts from repo so it should be up-to-date. 
Also I have installed Darktable 3.0.0 through this ppa : http://ppa.launchpad.net/ubuntuhandbook1/darktable/ubuntu
When using Darktable 2.6.3 I wasn't using LUA scripts so I cannot really tell if it would be working. I tried to force the 2.6.2 paquet in Synaptic but I got a warning about "darktable-dbg" and was scared I could mess up the database ...

Is there a simple debug procedure or anything to do to narrow down the issue ?

**Comment by wpferguson** [comment]
Each of the scripts has a block of comments at the start that explain what the script does, how it works, and how to use it. enfusedAdvanced, hugin, image_stack, and gimp all add additional export targets to the exporter.  If you go to the export selected module, and check the target storage drop down you should see "Edit with GIMP, "hugin panorama", "DRI or DFF image", and "image stack".

You don't need the `darktable = require "darktable"` line in your luarc file.  

If you have problems with the lua scripts and need to debug, you can start darktable from the command line with the -d lua switch to see the lua debugging output.

**Comment by maxence33** [comment]
Thanks a lot. This is clearly my mistake.
I have all these export options available and it seems to work as expected..

**Comment by maxence33** [comment]
Hi @wpferguson 
Sorry to bump again on this. 
Everything seemed fine after your last message but enfuseAdvanced kinda crashed Darktable. 
At restart unfortunately no script is available again. 

`darktable -d lua` gives

```
0,679723 LUA found enfuse executable at '/home/maxence'
sh: 1: /home/maxence: Permission denied
0,691122 LUA ERROR : /home/maxence/.config/darktable/lua/official/enfuse.lua:74: attempt to concatenate a nil value (local 'version')
```
Which didn't appear before enfuseAdvanced crash. 
Not sure how to fix. 
Though I have seen case #186 and will probably refrain from using enfuseAdvanced until further notice

**Comment by wpferguson** [comment]
This is also #213.  Start tools/executable_manager and clear the enfuse
executable.

**Comment by maxence33** [comment]
Thanks a lot, it is now fixed.

Now I know to revert any issue I may play again with enfuseAdvanced. 
I actually killed Dartkable after it was processing an enfusing for about 10 minutes. 
I though it was too long to be realistically still processing (especially compared to official/enfuse or LREnfuse in Windows) but I will go on and try again...
