### ISSUE TITLE
Issues with lib functions in file.lua

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/lua-scripts#206]
**Issue 1**
testing a script in both Windows and Linux, it seems function check_if_file_exists() fails, in particular when testing files with spaces in the filename in a NTFS drive:
1) on Windows check_if_file_exists(filepath) fails if filepath is not sanitized with sanitize_filename(), it always return false
2) on Linux  check_if_file_exists(filepath) fails if filepath is sanitized with sanitize_filename(), it always return true
either way, there is no coding that works in all cases, need to check which OS is running in my script, can't rely on the lib.

**Issue 2**
I include this other issue in the same report as I think the two are related
On both windows and Linux, calling sanitize_filename(filepath) on a filepath already sanitized produces a null output. In other word applying sanitize_filename() twice alway produces a null output.
To me this is incorrect, sanitize_filename(filepath) should return filepath untouched if already sanitized.

**Comment by wpferguson** [comment]
When was the last time you updated your lua scripts?  There were fixes to both the string library and the file library merged on Dec 16th that fixed some, if not all, of the issues you describe.

Can you paste the NTFS filename string, so I can test and see if I can recreate the problem.

**Comment by Mark-64** [comment]
I have tried to update the lib just yestedrday and none of the two issues seems to be fixed to me.
Here you have:
1) A simple script to test the issues
[test.lua.txt](https://github.com/darktable-org/lua-scripts/files/4010765/test.lua.txt)

2) the log output in Windows
[windows.log](https://github.com/darktable-org/lua-scripts/files/4010767/windows.log)
check_if_file_exists() fails with non sanitized filepaths containing spaces under Windows (rows 4 to 7)
double application of sanitize_filename results in a null string

3) the log under Linux
[linux.log](https://github.com/darktable-org/lua-scripts/files/4010779/linux.log)
check_if_file_exists() succeeds with non sanitized filepaths containing spaces under Linux (rows 4 and 5), however it fails with sanitized filepaths (row 8)
double application of sanitize_filename results in a null string

**Comment by wpferguson** [comment]
Thanks, I'll check it out

**Comment by wpferguson** [comment]
I just updated sanitize and is_not_sanitized in the string library which are called by sanitize_filename.  Can you check and see if the errors you noticed before are still present?  Thanks

**Comment by wpferguson** [comment]
The sanitize functions were just updated.  I ran your test script and got no errors, but those files don't exist on my system, so I'm not sure it's a valid test.  Please test after updating your lua-scripts and see if the issues are resolved.  Thanks.

**Comment by Mark-64** [comment]
tested successfully, thanks!
Close
