### ISSUE TITLE
Property image.is_raw fails when image path contains spaces

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/lua-scripts#209]
types.dt_lua_image_t.is_raw as is LUA manual 2.2.33 returns false for raw images, when the path contains spaces.
Tested on Ubuntu on images in a NTFS drive, DT 3.1 git master

**Comment by wpferguson** [comment]
How did you test this?  The test is performed against the database on images that have already been imported, not against files on disk.

Tested with 3.1 against a directory with a space in the path name and it worked correctly.  Tested on windows and on linux.

**Comment by wpferguson** [comment]
To test import a directory, then run the following script (with -d lua on the command line)

```
local dt = require "darktable"

for _,img in ipairs(dt.collection) do
  if img.is_raw then
    dt.print_log(img.filename .. " is raw")
  else
    dt.print_log(img.filename .. " is ldr")
  end
end

```

**Comment by Mark-64** [comment]
I have tested the above script over a few directories, see the result
[darktable-log.txt](https://github.com/darktable-org/lua-scripts/files/4027096/darktable-log.txt)
It fails mostly when there are spaces in filename or path but not only. It seems it doesn't like also names where there are no spaces, but other non alphanumeric characters, like "_" or "-".
DT 3.1 on Windows.

**Comment by Mark-64** [comment]
Let me also add a more complete log with filepaths.
[darktable-log.txt](https://github.com/darktable-org/lua-scripts/files/4027189/darktable-log.txt)

**Comment by Mark-64** [comment]
I also tried to remove library.db, disable any othe lua script other than test, reimport directories, but no luck.
It seems completely random, I am puzzled

**Comment by wpferguson** [comment]
What happens if you open a raw that is marked ldr in darkroom mode?  Check the demosaic module and see if it says something about only being used for raws.

I think this is a darktable bug, with something strange happening on import.

**Comment by Mark-64** [comment]
Nope, all the files are opened as normal RAWs, no difference in demosaic.

**Comment by wpferguson** [comment]
I'll need to look at the code and see where that value gets stored to the database to see if I can figure out why it's not always correct.

**Comment by wpferguson** [comment]
Looked at the code.  I was incorrect, it's not a database field.  There is a function name dt_image_is_raw() in src/common/image.c that checks the image flags and returns true or false based on whether the raw flag is set.

**Comment by wpferguson** [comment]
Let's try figuring out an image that is raw, but that the script says is ldr.  Open that folder in darktable, hover over, or select the image, then look at the flags in the image information panel and see if the r flag is set or not.

**Comment by Mark-64** [comment]
They are incorrect. For recognized RAWs it is "1...r..ap....", some of them even "1...r..ap...r", but the non-recognized RAWs are "1......ap...."

**Comment by Mark-64** [comment]
I finally managed to setup Darktable in Eclipse under Windows, so i could run the debugger.
It seem to me that the setup of flags is broken. 
The only place where the RAW flag is set is in dt_imageio_open_rawspeed() in imageio_rawspeed.cc, but that function is not called when importing images in lighttable. It is only called when opening in darkroom and there the flags are set correctly.
Try importing a new folder in lighttable, without entering darkroom, and check the flags in image information. The RAW flag is never set, and there might be other flags affected too.
This happens in Ubuntu as well. 
I will continue to investigate, I guess I should open a bug in Darktable.

**Comment by Mark-64** [comment]
[https://github.com/darktable-org/darktable/issues/4086](url)

**Comment by wpferguson** [comment]
I tried importing a new set of images.  The flags don't get set on import, but they do get set when the thumbnail preview is generated, because rawspeed has to open the image in order to generate the thumbnail.  I could see it change if I scrolled quickly down to images that didn't have a thumbnail yet, then watched the flags as the thumbnail was generated.  The flags updated when the thumbnail did.

**Comment by Mark-64** [comment]
Which version of DT are you using ?
In my 3.1 master some flags (RAW among them) are not set unless I enter darkroom. i checked in Windows and Ubuntu

**Comment by wpferguson** [comment]
I'm using git master last updated yesterday, on Ubuntu 18.04.

**Comment by Mark-64** [comment]
Looking at the code, dt_imageio_open_rawspeed() is called for some special formats, but not for all.
Can you please try with one Sony RAW, like [this](https://www.dpreview.com/reviews/image-comparison/download-image?s3Key=950e4131a8554b0684a7cfe9a2ca8a23.arw)?

**Comment by wpferguson** [comment]
Imported fine, flags are 0...r..ap...r on Ubuntu 18.04.  I have an older windows version, 2.6.2 or 3.   I'll try that and see what happens

**Comment by wpferguson** [comment]
Updated lua api manual with a warning about the flag not being set until the image is opened.  Should we close this?

**Comment by Mark-64** [comment]
Yes
