### ISSUE TITLE
lua script face_recognition - small issue

### ISSUE THREAD

**Issue by Yvan-56** [darktable-org/lua-scripts#210]
Hi, I have just tested the contrib face_recognition lua script.
I encountered a small issue related to locate: when passing the tolerance argument, my locate converts "." to "," going to command error.
This fix has helped me:
      dt.print_log ("Face recognition: Path to unknown images: " .. path)
 --  BEG - prevent converting "." to "," depending on locales, forced to C locale
      os.setlocale("C")
      local tolerance = dt.preferences.read(MODULE, "tolerance", "float")
      local command = bin_path ..  " --cpus " .. nrCores .. " --tolerance " .. tolerance .. " " .. knownPath .. " " .. path .. " > " .. OUTPUT
      dt.print_log("Face recognition: Running command: " .. command)
      os.setlocale()
 --  END - prevent converting "." to "," depending on locales, back to system locales

Hope this will help others.
Regards,
Yvan

**Comment by supertobi** [comment]
It would be cool if you could make a Pull request for the fix.

**Comment by Yvan-56** [comment]
I am not familiar with Git. I hope the way I have proposed the pull request is correct.
And hope this will help at the end.
Regards,
Yvan
