### ISSUE TITLE
'dtutils_string.sanitize' does not handle quote characters in input.

### ISSUE THREAD

**Issue by schwerdf** [darktable-org/lua-scripts#216]
The [`dtutils_string.sanitize` function](https://github.com/darktable-org/lua-scripts/blob/32d5240e5debec6cd9ccd0d361d9b061bd827e8f/lib/dtutils/string.lua#L195) does not produce a correct escaping of its input string in all cases. Specifically, on the POSIX side, trying to "sanitize" a filename with an apostrophe in it (such as I sometimes encounter when exporting by title) will result in a syntactically invalid command string. The Windows side seems similarly afflicted.

**Comment by wpferguson** [comment]
Thanks for reporting it.  I'm already working on the sanitize function, so I'll add this to my list of tests.

**Comment by wpferguson** [comment]
@schwerdf I rewrote sanitize and is_not_sanitized to make them more robust.  I tested it with a variety of strings, sanitized and unsanitized with single and multiple embedded quotes that were sanitized and not sanitized.  If you find a string that causes an error, please send it to me and reopen this issue.  Thanks

**Comment by schwerdf** [comment]
Since I do not have commit access to this repository, I cannot reopen the issue, but see pull request #218.
