### ISSUE TITLE
Apply crop to image from lua script in darkroom view

### ISSUE THREAD

**Issue by danilkhromov** [darktable-org/lua-scripts#226]
Is it possible to apply crop to image in darkroom mode from lua script?

I have a small app that can crop scanned negative by exposed image bounds. 
I wrote a script that allows me to crop selected images and put them to separate folder inside original import folder, but im wondering if there is a way to apply crop to an image in darkroom mode if external app can provide the bounds of crop area?
So far i only found that api allows to draw guides in crop mode.

**Comment by wpferguson** [comment]
The lua scripts are intended to run in lighttable view.  There are no hooks to any of the editing functions.

**Comment by danilkhromov** [comment]
@wpferguson thanks for clarification.
