### ISSUE TITLE
lua version

### ISSUE THREAD

**Issue by aster94** [darktable-org/lua-scripts#235]
hello,

which is the lua version used by the last darktable (3.0.1)?
from the docs it should be 5.2 https://www.darktable.org/usermanual/en/lua_chapter.html

**Comment by wpferguson** [comment]
It's 5.3.  The docs need updating.  It's on my to do list, but I haven't
got there yet.

Bill

**Comment by wpferguson** [comment]
Updated lua section of the user manual and submitted PR.
