### ISSUE TITLE
face_recognition: attempt to call a nil value reset_preferences

### ISSUE THREAD

**Issue by morsch** [darktable-org/lua-scripts#237]
Running `darktable -d lua` I get:  `LUA ERROR : .../.config/darktable/lua/contrib/face_recognition.lua:87: attempt to index a nil value (field 'unknown_tag')`

My luarc in its entirety: `require "contrib/face_recognition"`

The export option is not available.

I'm on the current master, a582f0229fee986fd3df1f3fe8cfcc05bb49c03a and darktable 3.0.1.

**Comment by wpferguson** [comment]
I believe this issue was fixed back in January.  Have you updated your scripts since then?
