### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by garethsnaim** [darktable-org/lua-scripts#242]
Sorry I am not a programmer, I downloaded git and installed and now I am trying to run the command to install this. I put in cd %LOCALAPPDATA%\darktable

It comes back with no such file or directory.

However there absolutely is that directory I checked. 

I did manage to get to the directory by copying it from explorer, and it seems to install

`$ git clone https://github.com/darktable-org/lua-scripts.git lua
Cloning into 'lua'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 2701 (delta 11), reused 7 (delta 3), pack-reused 2679
Receiving objects: 100% (2701/2701), 726.09 KiB | 1.87 MiB/s, done.
Resolving deltas: 100% (1738/1738), done.
`

When I start darktable there is no evidence anything happened. How would I know?

**Comment by wpferguson** [comment]
I'm sorry, I didn't see this until tonight.  I'm not sure how I missed it.

You can do the following:

from your home directory  cd %LOCALAPPDATA%\darktable
then copy lua\tools\script_manager.lua luarc

The next time you start darktable, script_manager will be in the bottom left corner of the lighttable view.  You can use script_manager to enable and disable scripts, as well as update them.
