### ISSUE TITLE
LUA: importing an image does not force a refresh of the new thumbtable

### ISSUE THREAD

**Issue by Mark-64** [darktable-org/lua-scripts#246]
With lua, the lib function dt.database.import() was used to force a refresh of lighttable so the image appeared immediately in the collection.
No longer so with the new thumbtable. The image is indeed imported, but the view isn't refreshed.
Forcing manually a refresh by changing back and forth film roll or going in and out of darkroom, makes the imported image show in the collection.
I posted the same issue (4889) on the darktable repo, as I am not sure where it is the appropriate place.

DT 3.1 git master on Windows 10

**Comment by wpferguson** [comment]
You can also click the collapse grouped images and then click it again which will show the imported image.  This is really a darktable issue, not a script issue.  I'll look at the code and see if I can figure it out.

**Comment by Mark-64** [comment]
Fixed in DT
