### ISSUE TITLE
DB maintenance confirmation windows issue when lua scripts are active

### ISSUE THREAD

**Issue by gadolf66** [darktable-org/lua-scripts#252]
When I have two lua scripts enabled and darktable database maintenance window should pop up on close, it doesn't pop up and darktable never closes (because it's waiting for user input)

To reproduce, activate face_recognition and photils, set up _database fragmentation ratio threshold_ to zero (to force the window to pop up all the time) and _check for database maintenance_ to _on close_ . Close darktable and reopen it, then close it again.
The database maintenance window doesn't show up, and darktable doesn't quit unless you kill the process.
To make it clear where darktable state is, call it from the terminal with -d all, so it shows clearly that it's waiting for user input on database maintenance.
This is related to [#5110](https://github.com/darktable-org/darktable/issues/5110#issue-619830710) 
OS: ubuntu 20.04
darktable 3.1.0~git1736.a6fc3dc68
Opencl: no
Second monitor: no

**Comment by wpferguson** [comment]
Could you try this with one of the scripts, then the other? Also could you try a different script and see if the problem repeats?

**Comment by gadolf66** [comment]
The issue seems to be on photils only.
Sorry having created a general issue for that. When I was working on the other issue I mentioned, I swear both scripts were causing the problem, but maybe I forgot to save lua.rc or something.
Now I let face_recognition enabled and did many open/close operations and the maitenance dialog showed up just fine.
I will address the issue on the photils thread in pixls.
Thanks.
