### ISSUE TITLE
batch rename

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/lua-scripts#269]
Started work on a batch rename script.  So far it's restricted to renaming files in the current film roll.  The problem isn't so much renaming the file as it is keeping the database in sync.  The xmp files also need renamed and ideally the filename in the xmp file needs changed.  That's not a problem in linux/macos because of multiple tools to edit the file from the script, but is in windows. I may just be able to do a re-import on the film roll to force the correction.

If we expand rename to allow specifying different paths, which in effect becomes a move, then things start to get a little hairy.  Since I'm moving files around, then I need to re-import all of the affected directories.  It also allows the user to do some ill advised things like sort files into directories based on ISO which would result in multiple film rolls named 100, 200, 400, 800, etc.

There is also no way to revert this at present.  I could add a tag with the original filename and the original film roll and then create an undo function that checks the tag and reverts the rename.

@schwerdf, others, thoughts?

**Comment by schwerdf** [comment]
I am confused. How exactly are you renaming these images, that it causes the database to go out of sync?

Re: the potential for sorting files into directories based on ISO, that is already fully supported in the import naming patterns, so supporting it here would probably not cause any major problems.

Re: the inability to revert the renaming, that is also true of any regular move or copy operation, especially when images from several directories are being moved into a single directory. One possible feature to address this would be some kind of preview showing how everything is going to be renamed -- this is common in dedicated batch renaming software.

**Comment by wpferguson** [comment]
My current steps for renaming are

change the filename in the database
rename the file on disk
rename the xmp file

the xmp file should be edited to change the filename inside, since that changed.  Doing an import may fix that.  Changing the xmp internal filename on linux/macos isn't a big deal, but it's not so easy on windows.

If I expand rename to allow moving files to different directories, then I have to remove the image from a film roll, move the file and the xmp file to the new directory, checking for collisions, then import all of the new/changed film rolls.

**Comment by schwerdf** [comment]
Why are you not just using the optional renaming parameters on `move_image` and `copy_image`? That obviates the need for any direct monkeying with the database, and I think it works just as well moving/copying files within the same film roll.

**Comment by wpferguson** [comment]
Hmmm...  Nice little undocumented feature.  I'll play with it and see what happens.  Thanks

**Comment by wpferguson** [comment]
@schwerdf try this and see what you think

[rename.zip](https://github.com/darktable-org/lua-scripts/files/4905856/rename.zip)

**Comment by Haribo-66** [comment]
I used the rename script the past couple of weeks and I love it!

This really closes a gap in functionality!

The only recommendation would be to be able to select and modify / use one of all of these various offered renaming suggestions instead of remembering them and to enter them manually ...

**Comment by schwerdf** [comment]
Sorry for my extreme tardiness in looking at this; it had fallen entirely off my radar. But ...

I just tried it out, and it worked well in sorting a batch of test images into a directory hierarchy by Exif date. There is only one improvement suggestion I have for the script itself: add a job progress bar, as a visible sign that the renaming process has begun.

I still think that this functionality should ultimately call into the core for the needed string substitutions (specifically to allow the use of the string manipulation variables), but what is supported by the existing script is enough to be useful, and it looks like there would be nothing preventing the addition of support for the string manipulation at a later stage.

**Comment by wpferguson** [comment]
Thanks @schwerdf for looking at it.  The progress bar is a good idea.  When I wrote the variable substitution I left the string manipulation as a TODO.

**Comment by wpferguson** [comment]
Fixed by #351
