### ISSUE TITLE
README - suggested update

### ISSUE THREAD

**Issue by heviiguy** [darktable-org/lua-scripts#286]
The instructions to run darktable from the command line are incorrectly identical in "Linux" and "Mac OS".

The following changes should be made:

### Linux

Open a terminal and start darktable with the command `darktable -d lua`. This provides debugging information to give you insight into what is happening.

### MacOS

Open a terminal and start darktable with the command `/Applications/darktable.app/Contents/MacOS/darktable -d lua`. This provides debugging information to give you insight into what is happening.

\* Please note that I've cloned this repository, made the changes to the README, uploaded the edited .md file to my own github account and tried, for the past 2 hours, to learn how to make a pull request. I've obviously not had enough coffee since the result has been fruitless. Hence, I've resigned myself to doing the next-best thing by posting here.

**Comment by supertobi** [comment]
Thanks, I've merged the README
