### ISSUE TITLE
Deprecate official/generate_image_txt.lua

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/lua-scripts#296]
The option to display the text sidecar over a zoomed image was removed from darktable by PR #7052, thus causing this script to have no purpose.  

I'm not sure how many, if any, people actually use this.  I propose keeping the script around for awhile after 3.4 is released to see if people want the PR reverted.  If no one raises a fuss, then the script will be removed.

**Comment by AlicVB** [comment]
not sure, this feature has not disappear, but is replaced by the use of $(SIDECAR_TXT) in overlay content.

**Comment by wpferguson** [comment]
Undeprecating....
