### ISSUE TITLE
Fujifilm ratings script doesn't support directories with spaces

### ISSUE THREAD

**Issue by pitbuster** [darktable-org/lua-scripts#300]
In the Spanish Darktable Telegram group, one user reported problems that we reduced to the `contrib/fujifilm_ratings.lua` script. After some digging into the script, it is clear that is not designed with filenames/directories that support spaces. I would happily provide a PR, but I can't test the script.

**Comment by wpferguson** [comment]
You can go ahead and submit a PR and I can test.  There is a function in the dtutils.file library called sanitize_filename() that will take care of the space problem.  You could probably download some Fuji files from the pixls.us Play Raw section if you want to test.
