### ISSUE TITLE
kml_export - request to add metadate title and description to KML

### ISSUE THREAD

**Issue by elman22** [darktable-org/lua-scripts#33]
Hello. It would be really nice if you could take metadata title and description and add them to the respective fields in generated KML. It certainly looks better in Google Earth with real title, not just filename. 

I any case I like this plugin very much. Keep up good work!

**Comment by supertobi** [comment]
I don't use title and description. How do I set them in darktable?

To get the title and description should be no problem, but we should use the file name as fall back.

http://redmine.darktable.org/projects/darktable/wiki/LuaAPI#title
http://redmine.darktable.org/projects/darktable/wiki/LuaAPI#description

**Comment by supertobi** [comment]
I've changed this and created a pull request.

**Comment by elman22** [comment]
If you want to use title and description, switch to lighttable and look for section "metadata editor" on the right side. There you can set title, description and other attributes.

Of course you should have file name as fall back. :)

Thank you.

**Comment by boucman** [comment]
fixed

**Comment by elman22** [comment]
Excellent, thank you very much.
