### ISSUE TITLE
kml_export - Wrong file names in generated kml

### ISSUE THREAD

**Issue by elman22** [darktable-org/lua-scripts#34]
I have RAW files with ARW extension. When I generate KMZ, all generated picture files have suffix _ARW, however KML references files with _JPG suffix.

Example:

Original file: DSC08817.ARW
Generated thumbnail: thumb_DSC08817_JPG.jpg
Generated picture: DSC08817.jpg (this is not referenced in KML at all and should be, since it has resolution I specified when exporting)
Generated smaller picture: DSC08817_JPG.jpg (this file is not useful, why is it generated?)

KMZ thumbnail reference: thumb_DSC08817_ARW.jpg
KMZ img src: DSC08817_ARW.jpg

**Comment by supertobi** [comment]
> I have RAW files with ARW extension. When I generate KMZ, all generated picture files have suffix _ARW, however KML references files with _JPG suffix.

That's because I use the darktable jpeg export.

> Example:
> 
> Original file: DSC08817.ARW
> Generated thumbnail: thumb_DSC08817_JPG.jpg
> Generated picture: DSC08817.jpg (this is not referenced in KML at all and should be, since it has resolution I specified when exporting)
> Generated smaller picture: DSC08817_JPG.jpg (this file is not useful, why is it generated?)

That's the image shown in the bubble, if you click on an image. The size is optimised to the bubble size of Marble. Bigger images look ugly here.

> KMZ thumbnail reference: thumb_DSC08817_ARW.jpg
> KMZ img src: DSC08817_ARW.jpg

Patches are welcome.

**Comment by elman22** [comment]
Let me summarize it so that I can get it right:

- thumb_DSC08817_JPG.jpg - this is resized to 96x96 and used as thumbnail
- DSC08817_JPG.jpg - this is resized to 438x438 and used as image in bubble when clicked on thumbnail
- DSC08817.jpg - this is resized to whatever set in darktable in export global options and used where?

**Comment by supertobi** [comment]
DSC08817.jpg is only used to create the other two file. It's not referenced in the kml file. At least it should not.

**Comment by supertobi** [comment]
Ahh, now I've seen, that the DSC08817.jpg is in the KMZ file. That's a bug, I'll fix that.

**Comment by boucman** [comment]
fixed

**Comment by elman22** [comment]
Excellent, thank you very much.
