### ISSUE TITLE
AutoGrouper crashes darktable when darktable is opened in darkroom mode

### ISSUE THREAD

**Issue by wpferguson** [darktable-org/lua-scripts#349]
AutoGrouper.lua hides the styles module when it starts.  This works fine as long as you are in lighttable mode, but if you are in darkroom mode, there is no styles module to hide, thus when you try it will crash darktable.

**Comment by jankirsten** [comment]
What is the reason that the styles module needs to hidden in the first place?

**Comment by wpferguson** [comment]
Fixed by #360
