### ISSUE TITLE
enfuseAdvanced not working with flatpak

### ISSUE THREAD

**Issue by orclex** [darktable-org/lua-scripts#366]
Hi,

I'm running darktable 3.6.1 as flatpak package on Kubuntu 21.04 and have enabled _enfuseAdvanced.lua_  by 
`require "contrib/enfuseAdvanced"`
in _.var/app/org.darktable.Darktable/config/darktable/luarc_
but I do not get the export target storage "DRI or DFF image". I also have installed enfuse in my local system. I assume the enfuseAdvanced lua script inside the flatpak sandbox isn't allowed to access the local installed binaries from enfuse. Am I right?
Is there a way to allow darktable to use these binaries?
Otherwise, it would be great to add depending binaries for lua scripts to the flatpak package too!

**Comment by wpferguson** [comment]
Since this is a problem with flatpaks, I'll close.
