### ISSUE TITLE
tools which is being deprecated

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/lua-scripts#369]
The following line:
https://github.com/darktable-org/lua-scripts/blob/d609823491587de9a4a623ef6e7023930f884c91/lib/dtutils/file.lua#L194

Is raising an issue:
/usr/bin/which: this version of `which' is deprecated; use `command -v' in scripts instead.

Indeed, recent Linux version have been deprecating `which` tool. The recommendation is to use `command -v` instead.

**Comment by wpferguson** [comment]
Got it.  Thanks

**Comment by TurboGit** [comment]
I did not create a PR as I'm not sure how to test that and "command -v" is not an external tool so not sure either if it will work with `popen()`.

**Comment by wpferguson** [comment]
My first thought was that I really need to finish migrating to 20.04.  My second thought was how am I going to test this?:)  I did a quick test on my Mac VM and it supports command -v as a built in.  I think this will probably work fine because lua runs external commands in a shell, IIRC.

**Comment by wpferguson** [comment]
Preliminary testing looks like it'll work fine.  Linux works and MacOS appears to work, but I have to do some work on the VM to get everything up to date and then I'll test again.
