### ISSUE TITLE
rename_images: thumbanil names aren't changed immediately

### ISSUE THREAD

**Issue by paolobenve** [darktable-org/lua-scripts#392]
darktable 3.8.x, scripts master

In the lighttable, I select various images, and I rename them with the script.

I get a desappearing notification saying that the images have been renamed - and actually they have been renamed -, but in the lighttable they keep having the original name.

**Comment by wpferguson** [comment]
tested on windows and linux and couldn't reproduce.  The images are renamed and collection is refreshed showing the new image names.
