### ISSUE TITLE
LUA-Script "AutoGrouper" is not visible

### ISSUE THREAD

**Issue by wwwFrank** [darktable-org/lua-scripts#393]
Darktable 3.8.1
Ubuntu 20.04
LUA-Script "AutoGrouper" is not visible.

~/.config/darktable/lua/contrib/AutoGrouper.lua  exists

~/.config/darktable/luarc  has a line  "require ' contrib/AutoGrouper" '

Not visible in lighttable view.
No output with 
  darktable -d lua

**Comment by wpferguson** [comment]
> ~/.config/darktable/luarc has a line "require ' contrib/AutoGrouper" '

Your quoting is incorrect.  Should be `require 'contrib/AutoGrouper'`

**Comment by wwwFrank** [comment]
Sorry, mistake by copying the line to the text above.

require 'contrib/AutoGrouper'

or

require "contrib/AutoGrouper"

don't work for me.

**Comment by wpferguson** [comment]
darktable 3.8.0+ uses lua 5.4.  Ubuntu 20.04 only has lua5.3.  By now there may be a back port.

**Comment by wwwFrank** [comment]
With DarkTable 4.2.1 on Ubuntu 22.04 LTS the LUA-AddOn "auto group" works for me. 
Issue may be closed.
