### ISSUE TITLE
Lua Script: ext_editor. Export to collection fails under Windows 11. 

### ISSUE THREAD

**Issue by Juangg77** [darktable-org/lua-scripts#401]
I've got an installation of Darktable 4.2 under Windows 11 Pro. I've installed git and the extension "ext_editor" through Darktable's script manager. When I try to export a picture to the current collection, the program throws the following error message:
Error moving file C:\Users\(my username)\AppData\Local\Temp\(filename)
I've realised that the TIFF file is created in the Temp folder but it seems the collection in Darktable is not updated with the new file.
My Images folder is backed up in Microsoft Onedrive so the pictures are stored locally but synched with the cloud, I don't know if that could be a problem but I'm giving all the possible details.
I don't know what the issue could be.

The details of my installation are as follows:
darktable version : 4.2.0
OS : Windows 11 Pro
CPU: Ryzen 5700U with Radeon Graphics
Memory : 16 Gb
Graphics card : Integrated AMD Vega Graphics
![export module](https://user-images.githubusercontent.com/121881554/210420086-d84c265a-6fa6-40eb-88f2-7cc46662f658.png)
![error](https://user-images.githubusercontent.com/121881554/210420449-c4638173-69aa-48a0-bafd-b91a865f36ba.png)

**Comment by Juangg77** [comment]
Update:
It seems that the issue has to do with the fact that my Images folder is under Onedrive. I've tried moving some pictures to a completely offline folder and the script works with them.
Should I close the report or is there any way to fix it?

**Comment by wpferguson** [comment]
Go ahead and leave it open for now.  I'll have to gen up a Win 11 machine and test it against one drive and see what is really happening and if there is any way to fix it.

**Comment by DarekGH** [comment]
Does c:\users\**_username_** has only pure english letters or it has language specific letters ?

Look at https://github.com/darktable-org/lua-scripts/issues/402

Darek

**Comment by Juangg77** [comment]
International letters only. There's no special character in it. In the Onedrive path, there is an "á".
I'm Spanish, so the pictures are stored in a folder named "Imágenes". Could that be the problem?

**Comment by DarekGH** [comment]
Put original file on OneDrive to another folder with only pure english letters and try again.
As I observe temp dir on drive C should be with only english letters, original folder should be with only english letters and file name should be with only english letters.
LUA is based on C and function which is used for copying/moving files do not recognized unicode but only old character coding (as I understud this https://stackoverflow.com/questions/54118507/lua-how-to-make-os-rename-os-remove-work-with-filenames-containing-unicode-ch  discussion) .

**Comment by Juangg77** [comment]
Thanks a lot DarekGH, that did the trick. I didn't realised that those characters would be a problem.

**Comment by DarekGH** [comment]
I hope here is a solution https://gist.github.com/Egor-Skriptunoff/2458547aa3b9210a8b5f686ac08ecbf0#file-utf8_filenames-lua
But I am not a programmer and I don't know what and where (which lua file) I should enter to achieve desired result.

**Comment by JAVIBARAKA** [comment]
Tengo exactamente el mismo problema con ext_editor y, no sé como solucionarlo. Alguien me puede ayudar?. Gracias.
![darktable_1](https://github.com/darktable-org/lua-scripts/assets/46654116/e8ced219-01cd-4425-a150-d619bde3ee1d)
![darktable_2](https://github.com/darktable-org/lua-scripts/assets/46654116/e4d9c8a5-6a5b-4119-bb2a-23da3aab10d2)
