### ISSUE TITLE
check_for_updates will not start

### ISSUE THREAD

**Issue by jc031699** [darktable-org/lua-scripts#413]
I have installed Lua 5.3.6, luarocks 3.8.0, openssl 3.1.0
All 32-bit versions
Used luarocks to install lua-cjson 2.1.0.10-1, luasec 1.3.1-1, luasocket 3.1.0-1

When I try to start check_for_updates, I get this error:

3.366971 LUA OpenInPS - Executable Path Preference: C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe
5.806769 LUA ERROR: script_manager.lua: activate: 367: Error loading official/check_for_updates 
5.806864 LUA ERROR: script_manager.lua: activate: 368: Error message: C:\Program Files\darktable\share\darktable/lua/socket.lua:12: module 'socket.core' not found:
	no field package.preload['socket.core']
	no file 'C:\Users\J\AppData\Roaming\LuaRocks\share\lua\5.3\socket\core.lua'
	no file 'C:\Users\J\AppData\Roaming\LuaRocks\share\lua\5.3\socket\core\init.lua'
	no file 'C:\Program Files\darktable\share\darktable/lua/socket\core.lua'
	no file 'C:\Users\J\AppData\Local\darktable/lua/socket\core.lua'
	no file 'C:\Users\J\AppData\Roaming\LuaRocks\lib\lua\5.3\socket\core.dll'
	no file 'C:\Users\J\AppData\Roaming\LuaRocks\lib\lua\5.3\socket.dll' 

I have tried moving socket\core.dll from my lua lib directory to the roaming\luarocks directory above, but it says it is not a win32 application.  The closest I have gotten is a purported win64 luasocket core.dll file found online, which when placed in that location says something about the library not being found etc.  (I don't remember exactly, but it seemed to take it as an acceptable application.)

**Comment by wpferguson** [comment]
What version of darktable are you using?  Since darktable 3.8.0 darktable uses Lua 5.4

**Comment by jc031699** [comment]
I tried Lua 5.4, same problem.  Currently on Lua 5.3 since the Lua script says to install 5.3 versions of luasec and cjson.



On Apr 21, 2023, at 8:05 PM, wpferguson ***@***.***> wrote:

﻿
What version of darktable are you using? Since darktable 3.8.0 darktable uses Lua 5.4

**Comment by wpferguson** [comment]
I have lua5.4 installed.  I installed `luarocks` then installed the `luasec` and `lua-cjson` packages.  The check_for_updates script ran fine.  I'm using Ubuntu 22.04.  I'll try testing on windows.

**Comment by wpferguson** [comment]
The luasec package needs to be compiled and it requires the openssl development libraries, so in order to do that you would need an msys2 build environment.

**Comment by jc031699** [comment]
I installed luasec using Luarocks, by linking to my OpenSSL 32 bit directory “openssl_dir=“

The OpenSSL was installed using an exe from here:

https://slproweb.com/products/Win32OpenSSL.html

Luasec was installed without any problems

On Apr 22, 2023, at 9:28 AM, wpferguson ***@***.***> wrote:

﻿
The luasec package needs to be compiled and it requires the openssl development libraries, so in order to do that you would need an msys2 build environment.

**Comment by wpferguson** [comment]
```
luarocks list

Rocks installed for Lua 5.4
---------------------------

lua-cjson
   2.1.0.10-1 (installed) - /usr/local/lib/luarocks/rocks-5.4

luasec
   1.3.1-1 (installed) - /usr/local/lib/luarocks/rocks-5.4

luasocket
   3.1.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.4
```
Do a `luarocks list` command and see what is installed

**Comment by jc031699** [comment]
J Cheng

On Apr 22, 2023, at 1:39 PM, wpferguson ***@***.***> wrote:

﻿
luarocks list

Rocks installed for Lua 5.4
---------------------------

lua-cjson
   2.1.0.10-1 (installed) - /usr/local/lib/luarocks/rocks-5.4

luasec
   1.3.1-1 (installed) - /usr/local/lib/luarocks/rocks-5.4

luasocket
   3.1.0-1 (installed) - /usr/local/lib/luarocks/rocks-5.4
Do a luarocks list command and see what is installed

**Comment by wpferguson** [comment]
Updated documentation and script comments to use Lua 5.4 luarocks.
