### ISSUE TITLE
RL_out_sharp doesn't preserve EXIF metadata

### ISSUE THREAD

**Issue by jsmucr** [darktable-org/lua-scripts#493]
Windows 10
DT 4.8+ master (`c18491922c17c32d0544da0365368072bf5d75d5`)
LUA scripts master (`3bb4e9c59a422f17eb1850dff4d5bc0c2075fcef`)
G'Mic 3.4.0

EXIF metadata isn't preserved for TIFF nor for JPEG export. Standard DT JPEG output works fine.

**Comment by wpferguson** [comment]
The problem is that G'Mic, which does the sharpening,  doesn't preserve EXIF data and has no provisions to do so according to the author.

There is a way to work around this by using exiftool to extract the metadata from the original image and then apply it to the sharpened image.

**Comment by jsmucr** [comment]
@wpferguson Thank you for such a fast fix. :-) I haven't had a chance to test it yet though, likely due to #492 because I'm getting this error:
```
LUA ERROR Windows command failed: unable to create batch file
```
