### ISSUE TITLE
"Color matrix missing" message appearing when trying to enter darkroom - Sony Alpha 7 IV ILCE-7M4

### ISSUE THREAD

**Issue by enotyaR** [darktable-org/lua-scripts#508]
When trying to enter darkroom mode, a message appears stating that the color matrix is missing
![Screenshot 2024-09-06 175930](https://github.com/user-attachments/assets/9050e0cd-728d-4ffa-894c-ec47033462d7)

**Comment by wpferguson** [comment]
You should raise this issue at https://github.com/darktable-org/darktable/issues.  You might look through the open issues because I believe that it has already been raised.

**Comment by enotyaR** [comment]
My bad! I thought I searched there but clearly missed. Thanks for answering!
