### ISSUE TITLE
avoid new translations and ensure proper language support

### ISSUE THREAD

**Issue by TurboGit** [darktable-org/lua-scripts#525]
https://github.com/darktable-org/lua-scripts/blob/e3595676202b9c1bd57b494e0c895a673f848233/lib/dtutils/string.lua#L868

All those strings should add EXIF into the translation. Indeed in some language like French "EXIF year" will be translated to "Année EXIF".

I propose to keep the whole string as done in current dt code as this will avoid new translations.

`"$(EXIF.YEAR) - EXIF year"` is already translated in all languages, better keep this form.

This must be done for all similar strings.

**Comment by wpferguson** [comment]
Real life buried me for a few weeks, but I've mostly dug out now.

I'll try and have all the translation stuff updated by Monday.  I'll tag you after I've made the changes and they are ready for review.

**Comment by wpferguson** [comment]
@TurboGit instead of doing `string.format`  for each of the variables, I'll just steal the strings from gtkentry.c so it should be a match and nothing new to translate.
