### ISSUE TITLE
kml_export - packs to kmz all files from dt.configuration.tmp_dir

### ISSUE THREAD

**Issue by elman22** [darktable-org/lua-scripts#53]
When I take snapshot in darkroom, darktable saves this snapshot to dt.configuration.tmp_dir and file dt_snapshot_\*.png is created. When I use kml_export script, it also uses dt.configuration.tmp_dir and at the end packs everything into .kmz. Including dt_snapshot_\*.png.

Maybe you could create new folder inside dt.configuration.tmp_dir, so that your files don't mix with snapshots.

**Comment by supertobi** [comment]
I don't know when I'll find the time to fix this. You could try to change the line 110 to look like this:

> exportDirectory = dt.configuration.tmp_dir .. "/kmz_export"
https://github.com/darktable-org/lua-scripts/blob/master/contrib/kml_export.lua#L110

It would even better if we would use a unique directory name. Perhaps this works:
https://luaposix.github.io/luaposix/modules/posix.stdlib.html#mkdtemp

Please report back if this fixes the problem.

**Comment by supertobi** [comment]
The line number changed and is now 182 and the same change has to go to line 327 too.
