### ISSUE TITLE
kml_export - unable to open kmz in Google Earth (Linux)

### ISSUE THREAD

**Issue by elman22** [darktable-org/lua-scripts#54]
Problem is that I use diacritics in folders and when I import film roll into darktable, it also has diacritics in the name. Consequently when kml is generated, name with diacritics is used. If this is the case, Google Earth will not open kmz. 

Maybe it's Google's bug, but you could strip diacritics from kml name.

Error - Etiópia 2016.kml
Working - Etiopia 2016.kml

Thanks

**Comment by supertobi** [comment]
I don't know when I'll find the time to fix this. But if you are interested in fixing this yourself this links may help:

http://lua-users.org/lists/lua-l/2007-04/msg00346.html
https://forums.coronalabs.com/topic/43048-remove-special-characters-from-string/
http://lua.2524044.n2.nabble.com/removing-diacritical-marks-from-strings-td7626507.html

**Comment by supertobi** [comment]
I've just tested it with Google Earth 7.1.2.2041 and it works with the filename "Etiópia 2016.kml". What is your Google Earth version?

**Comment by elman22** [comment]
Hi, mine is Google Earth 7.1.4.1529, so it looks like it's newer - I use the one from AUR.
BTW sorry about not answering to your previous comment. I couldn't find time to study it as well :(

**Comment by supertobi** [comment]
I've tested it again. It works if you open the kml file with the file open dialogue but not if you use the command line. 

I think I've fix the problem, please test.

**Comment by elman22** [comment]
Unfortunately no kmz is generated. I see that thumbnails are generated, but they remain in ~/.local/tmp.

**Comment by supertobi** [comment]
You need the version before the last changes from boucman:
https://github.com/darktable-org/lua-scripts/blob/204868d73369673a5c7e992aa27926e463d349b3/contrib/kml_export.lua

**Comment by elman22** [comment]
Well this version does create kmz (Google Earth opens it when I check "Open file after export"), but it doesn't place it in folder I specified in settings.

**Comment by supertobi** [comment]
That's strange. I've tested it now several times and it works here fine. What is the name of the output folder in the settings, and where does the script place the KMZ files?

**Comment by elman22** [comment]
I use folder 
lua/kml_export/ExportDirectory=/home/elman/Pictures/Travelling

**Comment by supertobi** [comment]
Are there any error messages, if you call darktable from the command line with:
`darktable -d lua`

**Comment by elman22** [comment]
When exporting 7 ARW images, I got KMZ with just KML file and no images

> LUA ERROR Will try to export KML file now
        zip warning: name not matched: /home/elman/.local/tmp/thumb_DSC11171_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/DSC11171_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/thumb_DSC11183_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/DSC11183_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/thumb_DSC11200_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/DSC11200_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/thumb_DSC11203_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/DSC11203_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/thumb_DSC11178_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/DSC11178_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/thumb_DSC11191_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/DSC11191_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/thumb_DSC11192_ARW.jpg
        zip warning: name not matched: /home/elman/.local/tmp/DSC11192_ARW.jpg
  adding: Etiopia 2016.kml (deflated 85%)
test of /home/elman/Pictures/Travelling/Etiopia 2016.kmz OK

When exporting 2 JPEG, I got correct KMZ that opened in Google Earth

> LUA ERROR Will try to export KML file now
  adding: Etiopia 2016.kml (deflated 70%)
  adding: thumb_DSC11023-DSC10389_JPG.jpg (deflated 1%)
  adding: DSC11023-DSC10389_JPG.jpg (deflated 0%)
  adding: thumb_DSC11023-DSC10393_JPG.jpg (deflated 2%)
  adding: DSC11023-DSC10393_JPG.jpg (deflated 0%)
test of /home/elman/Pictures/Travelling/Etiopia 2016.kmz OK

**Comment by supertobi** [comment]
That's because I use convert (ImageMagic) to convert the images and convert doesn't support ARW files. Please file a new issue for this problem. I think we should add a check and stop the export if any thing else then jpeg is selected. But this has nothing to do with this issue.
