### ISSUE TITLE
dbmaint not working?

### ISSUE THREAD

**Issue by abruenin** [darktable-org/lua-scripts#543]
I installed dbmaint. Clicking on scan seems to do nothing, no matter if film rolls or images is selected.

**Comment by wpferguson** [comment]
What do you expect it to do?

If you select images then the current film roll is checked to make sure all the images that the database knows about, for that film rolls, exist.

If you select film rolls, then all the film rolls that the database knows about are checked to make sure they exist.

If something is missing, then it's listed and the user is given way to correct it.

**Comment by abruenin** [comment]
I have an album with some images missing. I thought, it would get any feedback on what images are missing.  But nothing happens after i click on scan

**Comment by wpferguson** [comment]
Are the missing images displayed as skulls?

Can you give me a set of steps that I can use to try and reproduce?

**Comment by abruenin** [comment]
No, they are not displayed as skulls. But when I try to open one, I get the message 'image <file-name is currently unavailable'
Normally, I would expect them to be displayed as skulls from there, but they won't. Could that be some problem with my database?
My steps are just open that collection, in dbmaint choose images and click scan.

**Comment by abruenin** [comment]
OK, looks like something else is wrong in my environment. I fix that first and try again, sorry for bothering

**Comment by wpferguson** [comment]
> sorry for bothering

Not a problem.  I try and think of everything when I write a script, but users often are able to find things I didn't think of :smile:
