### ISSUE TITLE
kml_export - wrong handling of image formats other than jpg

### ISSUE THREAD

**Issue by elman22** [darktable-org/lua-scripts#58]
How to reproduce:
1. Open ARW file in darktable, e.g. DSC10661.ARW
2. Select KML/KMZ export and use format options JPEG
3. Press export

Exported image is saved as JPEG and ImageMagick converts it to JPEG, e.g. DSC10661_JPG.jpg is created. kml_export expects to zip file DSC10661_ARW.jpg and fails (also name DSC10661_ARW.jpg is used in kml and references non existing image)

If I change format options to TIFF. Exported image is saved as TIFF and ImageMagick converts it to JPEG, e.g. DSC10661_TIF.jpg is created. kml_export expects to zip file DSC10661_ARW.jpg and fails.

So kml_export should check format options and expect correct file name.

**Comment by supertobi** [comment]
I think I must use exported_image and not image here:
https://github.com/darktable-org/lua-scripts/blob/master/contrib/kml_export.lua#L332

I'll have a closer look to it later.
@elman22 If you can would give me your email address I could send you test versions.

**Comment by elman22** [comment]
I fixed it in issue #59 . See attachment in my post.
