### ISSUE TITLE
[gimp.lua] field "execute" not found for type dt_lua_singleton_control

### ISSUE THREAD

**Issue by manu-p** [darktable-org/lua-scripts#64]
Hi, here follows the trace I get when I try to "Edit with GIMP" from DT: 

`~$ darktable -d lua
LUA ERROR true checkIfBinExists: gimp
LUA ERROR gimp /home/manu/.local/tmp/Jam\ au\ Joug-160721-_K5_3956.tif 
LUA ERROR : /home/manu/.config/darktable/lua/gimp.lua:203: field "execute" not found for type dt_lua_singleton_control

stack traceback:
	[C]: in function '__index'
	/home/manu/.config/darktable/lua/gimp.lua:203: in function </home/manu/.config/darktable/ua/gimp.lua:179>
`

**Comment by supertobi** [comment]
Which darktable version do you use?
Which Gimp version do you use?
Do you use the latest version of the script?

**Comment by manu-p** [comment]
Hi, 
DT 2.0.5
Gimp 2.9.5
I downloaded yesterday the lua script from here.

**Comment by supertobi** [comment]
Do you have the "official/yield.lua" required before the gimp.lua script? If not pleas do so. This is necessary if you don't use dt master.

**Comment by manu-p** [comment]
I didn't know official/yield.lua was required, I just downloaded it in $HOME/.config/darktable/lua and the traceback is the same:

$ darktable -d lua
LUA ERROR true checkIfBinExists: gimp
LUA ERROR gimp /home/manu/.local/tmp/Jam\ au\ Joug-160721-_K5_3962.tif 
LUA ERROR : /home/manu/.config/darktable/lua/gimp.lua:203: field "execute" not found for type dt_lua_singleton_control

stack traceback:
	[C]: in function '__index'
	/home/manu/.config/darktable/lua/gimp.lua:203: in function </home/manu/.config/darktable/lua/gimp.lua:179>

**Comment by chrik5** [comment]
You need to require "yield.lua" before "gimp.lua" in your $HOME/.config/darktable/luarc. Is this the case?

require "yield"
require "gimp"

**Comment by manu-p** [comment]
OK thanks, it works now. 

Was this information about yield required for gimp.lua explained somewhere ? I didn't find it in gimp.lua. If not, maybe this would help to mention it somewhere easy to find.
