### ISSUE TITLE
API version not compatible with current darktable master

### ISSUE THREAD

**Issue by schenlap** [darktable-org/lua-scripts#94]
Using gimp script i get the following error
LUA ERROR Module lib/dtutils.file is not compatible with API 5.0.0-dev

These file are not compatible with current darktable master API:

include_all.lua:36:dt.configuration.check_version(...,{3,0,0})
official/check_for_updates.lua:34:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/save_selection.lua:37:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/delete_long_tags.lua:32:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/selection_to_pdf.lua:39:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/enfuse.lua:40:dt.configuration.check_version(...,{3,0,0},{4,0,0})
official/image_path_in_ui.lua:32:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/generate_image_txt.lua:41:dt.configuration.check_version(...,{2,1,0},{3,0,0},{4,0,0})
official/copy_paste_metadata.lua:30:dt.configuration.check_version(...,{3,0,0},{4,0,0})
tools/get_lib_manpages.lua:13:dt.configuration.check_version(...,{3,0,0})
tools/get_libdoc.lua:9:dt.configuration.check_version(...,{3,0,0})
lib/dtutils/file.lua:26:dt.configuration.check_version(...,{3,0,0},{4,0,0})
examples/hello_world.lua:30:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
contrib/geoToolbox.lua:33:dt.configuration.check_version(...,{3,0,0},{4,0,0})
contrib/rate_group.lua:44:dt.configuration.check_version(...,{3,0,0},{4,0,0})
contrib/video_mencoder.lua:38:dt.configuration.check_version(...,{2,0,1},{3,0,0},{4,0,0})
contrib/slideshowMusic.lua:32:dt.configuration.check_version(...,{2,0,2},{3,0,0},{4,0,0})

**Comment by supertobi** [comment]
Some of these are fixed. @schenlap could you please update the list.

**Comment by schenlap** [comment]
@supertobi, here it is

include_all.lua:36:dt.configuration.check_version(...,{3,0,0})
official/check_for_updates.lua:34:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/save_selection.lua:37:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/delete_long_tags.lua:32:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/selection_to_pdf.lua:39:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/enfuse.lua:40:dt.configuration.check_version(...,{3,0,0},{4,0,0})
official/image_path_in_ui.lua:32:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/generate_image_txt.lua:41:dt.configuration.check_version(...,{2,1,0},{3,0,0},{4,0,0})
official/copy_paste_metadata.lua:30:dt.configuration.check_version(...,{3,0,0},{4,0,0})
tools/get_lib_manpages.lua:13:dt.configuration.check_version(...,{3,0,0})
tools/get_libdoc.lua:9:dt.configuration.check_version(...,{3,0,0})
contrib/rate_group.lua:44:dt.configuration.check_version(...,{3,0,0},{4,0,0})
contrib/fujifilm_ratings.lua:30:dt.configuration.check_version(..., {4,0,0})
contrib/cr2hdr.lua:38:darktable.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
contrib/clear_GPS.lua:45:dt.configuration.check_version(...,{3,0,0},{4,0,0})
contrib/slideshowMusic.lua:32:dt.configuration.check_version(...,{2,0,2},{3,0,0},{4,0,0})

**Comment by supertobi** [comment]
contrib/rate_group.lua:44:dt.configuration.check_version(...,{3,0,0},{4,0,0})
contrib/fujifilm_ratings.lua:30:dt.configuration.check_version(..., {4,0,0})
contrib/cr2hdr.lua:38:darktable.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
contrib/clear_GPS.lua:45:dt.configuration.check_version(...,{3,0,0},{4,0,0})
contrib/slideshowMusic.lua:32:dt.configuration.check_version(...,{2,0,2},{3,0,0},{4,0,0})

official/check_for_updates.lua:34:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/copy_paste_metadata.lua:30:dt.configuration.check_version(...,{3,0,0},{4,0,0})
official/delete_long_tags.lua:32:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/enfuse.lua:40:dt.configuration.check_version(...,{3,0,0},{4,0,0})
official/generate_image_txt.lua:41:dt.configuration.check_version(...,{2,1,0},{3,0,0},{4,0,0})
official/image_path_in_ui.lua:32:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/save_selection.lua:37:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})
official/selection_to_pdf.lua:39:dt.configuration.check_version(...,{2,0,0},{3,0,0},{4,0,0})

ToDo for someone who knows how to test this scripts:
include_all.lua:36:dt.configuration.check_version(...,{3,0,0})
tools/get_lib_manpages.lua:13:dt.configuration.check_version(...,{3,0,0})
tools/get_libdoc.lua:9:dt.configuration.check_version(...,{3,0,0})

**Comment by wpferguson** [comment]
I'll do a PR tonight unless someone beats me to it.


Bill
